blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path("", include("blogposts.urls")),
]

blogposts/urls.py
"""Defines the url patterns for the app."""

from django.urls import path

from . import views

app_name = "blogposts"
urlpatterns = [
        #home page
        path("", views.index, name="index"),
        #Display all posts
        path("posts/", views.posts, name="posts"),
        #Display the content of a post
        path("posts/<int:post_id>/", views.post, name="post"),
        #Form to add new posts
        path("posts/new_post/", views.new_post, name="new_post"),
        #Form to make edits to posts
        path("posts/edit_post/<int:title_id>/", views.edit_post, name="edit_post")
        ]

users/urls.py
""" Defines URL patterns for users."""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
        # Include default auth urls.
        path("", include("django.contrib.auth.urls")),
        #Registration page
        path("register/", views.register, name="register"),
]

blogposts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    """A blog post."""
    title = models.CharField(max_length=256)
    post = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

users/models.py
from django.db import models

# Create your models here.

blogposts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    """Form to make new posts."""
    class Meta:
        model = Post
        fields = ["title", "post"]
        labels = {"title": "Title", "post": "Content"}

blogposts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Post
from .forms import PostForm

def index(request):
    """The home page"""
    title = Post.objects.order_by("-date")
    context = {"title": title}
    return render(request, "blogposts/index.html", context)

def posts(request):
    """Page to display all the posts."""
    title = Post.objects.order_by("date")
    context = {"title": title, "user": request.user}
    return render(request, "blogposts/posts.html", context)


def post(request, post_id):
    """Page to display content of a post."""
    title = Post.objects.get(id=post_id)
    content = title.post
    context = {"title": title, "content": content, "user": request.user, "owner": title.owner}
    return render(request, "blogposts/post.html", context)


@login_required
def new_post(request):
    """Form to make new posts."""
    if request.method != "POST":
        #No data submitted; create a blank form.
        form = PostForm()
    else:
        #POST data submitted; process date
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect("blogposts:posts")

    #Display a blank for invalid form.
    context = {"form": form}
    return render(request, "blogposts/new_post.html", context)


@login_required
def edit_post(request, title_id):
    """A form to edit posts."""
    title = Post.objects.get(id=title_id)
    content = title.post

    if request.method != "POST":
        #Initial request; pre-fill form with the current entry.
        form = PostForm(instance=title)
    else:
        #POST data submitted; process data.
        
        check_post_owner(request, title)
        form = PostForm(instance=title, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogposts:post", post_id=title.id)

    context = {"title": title, "content": content, "form": form}
    return render(request, "blogposts/edit_post.html", context)


def check_post_owner(request, title):
    """Restricts page to only owners."""
    if request.user != title.owner:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user account."""
    if request.method != "POST":
        # Display blank registration form 
        form = UserCreationForm()
    else:
        #Process complete form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect("blogposts:index")

    #Display a blank or invalid form
    context = {"form": form}
    return render(request, "registration/register.html", context)

blogposts/templates/blogposts/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1,
				shrink-to-fit=no">
	<title>Reads</title>		
	{% bootstrap_css %}
	{% bootstrap_javascript jquery="full" %}
	
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
		<a class="navbar-brand" href="{% url "blogposts:index" %}">Reads</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-item" href="{% url 'blogposts:posts' %}">
						Posts</a></li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text">Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">
						Log out</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">
						Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">
						Log in</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<main role="main" class="container">
		<div class="pb-2 mb-2 border-border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>
</body>

</html>

blogposts/templates/blogposts/edit_post.html
{% extends "blogposts/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2>Edit post</h2>
{% endblock page_header %}

{% block content %}
	<form class="form" action="{% url 'blogposts:edit_post' title.id %}" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button class="btn btn-primary" name="submit">Save changes</button>
		{% endbuttons %}
	</form>
{% endblock content %}

blogposts/templates/blogposts/index.html
{% extends "blogposts/base.html" %}

{% block page_header %}
	<div class="jumbotron">
		<h1 class="display-3">Read and be read.</h1>

		<p class="lead">Make posts about anything at all and read post 
		posts about anything at all. Just post for others to read and 
		read what others have posted.</p>

		{% if not user.is_authenticated %}
			<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
				role="button">Resigter &raquo;</a>
		{% else %}
			<a class="btn btn-lg btn-primary" href="{% url 'blogposts:posts' %}"
				role="button">Read &raquo;</a>
		{% endif %}

	</div>
{% endblock page_header %}

{% block content %}
	<div>
		<h4>Most Recent Posts</h4>
		<div class="row">
		{% for title in title|slice:"3" %}
  			<div class="col-sm-4">
				<div class="card" >
					<div class="card-body">
						<h5 class="card-title"> {{ title }}</h5>
						<h6 class="card-subtitle mb-2 text-muted">{{ title.date|date:"M d, Y H:i" }}</h6>
						<p class="card-text">{{ title.post|truncatechars:150 }}</p>
						<a href="{% url 'blogposts:post' title.id %}" class="card-link">Read</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

blogposts/templates/blogposts/logged_out.html
{% extends "blogposts/base.html" %}

{% block content %}
<p>You have been logged out. Thank you for visiting!</p>
{% endblock content %}

blogposts/templates/blogposts/new_post.html
{% extends "blogposts/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2>Add a new post</h2>
{% endblock page_header %}

{% block content %}

<form class="form" action="{% url 'blogposts:new_post' %}" method="post">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
		<button class="btn btn-primary" name="submit">Post</button>
	{% endbuttons %}
</form>

{% endblock content %}

blogposts/templates/blogposts/post.html
{% extends "blogposts/base.html" %}


{% block content %}

	<div class="card mb-3">
		<h3 class="card-header"> {{ title }}</h3>
		<div class="card-body">
			<p>{{ content|linebreaks }}</p>
		</div>
		<div class="card-footer text-muted text-center">
			<small>
			<strong>
			{% if owner != user %}
				Post by: {{ title.owner }}.
			{% else %}
				Post by: you.
				<a href="{% url 'blogposts:edit_post' title.id %}">Edit post</a>
			{% endif %}
			</strong>
			<p>{{ title.date|date:"M d, Y H:i" }}</p>
			</small>

		</div>
	</div>

{% endblock content %}

blogposts/templates/blogposts/posts.html
{% extends "blogposts/base.html" %}

{% block page_header %}
	<h1>Posts</h1>
{% endblock page_header %}


{% block content %}
	{% for title in title %}
		<div class="card mb-3">
			<div class="card-header">
				<h4>
					<a href="{% url 'blogposts:post' title.id %}">{{ title }}</a>
				</h4>
				{% if title.owner == user %}
					<small>
						<a href="{% url 'blogposts:edit_post' title.id %}">
							edit post</a>
					</small>
				{% endif%}
			</div>
			<div class="card-body">
				<h6>{{ title.date|date:'M d, Y H:i' }}</h6>
				{{ title.post|truncatechars:150 }}
			</div>
		</div>
	{% empty %}
		<li><h3>No posts yet</h3></li>
	{% endfor %}
	{% if user.is_authenticated %}
		<a href="{% url 'blogposts:new_post' %}">Add post</a>
	{% endif %}
{% endblock content %}